server:
  servlet:
    context-path: /demo
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #login mock
          issuer-uri: http://localhost:8082
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: postgresql
    properties:
      hibernate:
        types:
          print:
            banner: false
        jdbc:
          time_zone: Europe/Paris
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_SCHEMA:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ${DB_SCHEMA:postgres}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, env, prometheus, swagger, health

info:
  app:
    name: @project.name@
    version: @project.version@
